import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

// NEXT-INTL IMPORTS
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * SSG (STATIC SITE GENERATION) PRERENDERING
 * * This function is automatically called by Next.js during `npm run build`.
 * It tells the compiler to prerender static HTML pages for all supported locales
 * defined in `routing.ts` (e.g., creating physical static paths for /uk and /en).
 */
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  // ASYNC LOCALE RESOLUTION (Next.js 15/16 standard)
  const { locale } = await params;

  // SECURITY GUARD / VALIDATION
  // Checks if the URL locale exists in our allowed config. If not (e.g., /xyz/about), triggers 404.
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  // SERVER-SIDE LOCALE BINDING
  // Explicitly locks the current locale context for Server Components rendering on this request.
  // Crucial for keeping pages static (SSG) instead of dropping into dynamic on-demand rendering.
  setRequestLocale(locale);

  // FETCH TRANSLATION DATA
  // Dynamically loads the corresponding JSON messages file (via `src/i18n/request.ts`)
  // to make translation keys available to the rendering tree.
  const messages = await getMessages();

  return (
    <html
      lang={locale} // DYNAMIC HTML LANGUAGE TAG (Switches between 'uk', 'en', etc.)
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* CLIENT-SIDE INTERNATIONALIZATION CONTEXT
            Provides the loaded JSON messages to any nested Client Components (`'use client'`)
            so they can use synchronous hooks like `useTranslations()`. */}
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
